### PR TITLE
Add several new features, and clarify them in the README.

### PR DESCRIPTION
**Pull request by impinball**
@russmatney WDYT?

I added several new features, each fully tested (should all be passing) and
explained in the README. The goal for all of this is in two parts:

1.  Allow for consumers to parse more file types. That will future-proof this
    module quite a bit. This means you can use it like this:

    ```coffee
    # env.cson
    NODE_ENV: 'debug'

    # gulpfile.coffee
    gulp = require 'gulp'
    nodemon = require 'gulp-nodemon'
    env = require 'gulp-env'

    gulp.task 'nodemon', ->
      env
        file: '.env.json'
        vars: {} # any variables you want to overwrite

      nodemon
        script: 'server.coffee'
        ext: 'coffee html'
        # other config ...
    ```

2.  Allow for consumers to parse files as if they were a different type than
    they really are (within the limitations of Node.js itself). This allows for
    a lot more flexibility, which is often needed, but is always nice.

    ```yaml
    # .env
    NODE_ENV: 'debug'
    MONGO_URI: 'mongodb://localhost:27017/testdb'
    ```

    ```js
    var env = require('gulp-env');
    var jsyaml = require('js-yaml');

    env({
      file: '.env',
      handler: jsyaml.safeLoad,
    });
    ```

3.  The part of returning a no-op stream was more of an after-thought, and not
    really because of one of the main reasons. It's mostly for convenience,
    and making it a little more explicitly Gulp-friendly.

Here's a list of the new features:

  - Passing a string filename as the default. This is one of the two common
    cases, and is easy to detect.
      - Technically, the argument is coerced into a string unless it's
        `typeof object`.

  - `env.set(vars)`, a shortcut for just setting hardcoded variables without
    loading a file. This is also an alias for `env({vars: vars})`, the other of
    the two most common use cases. It's also easier to use than
    `util.extend(process.env, vars)`, since you can use it in the middle of a
    Gulp pipeline.

  - Support for .ini files. This fixes the first half of #5.

  - Support for parsing files as alternate types (currently only `.ini` and
    `.json`, but can easily be modified to support YAML, etc.). This fixes the
    second half of #5.

  - Hooks for parsing files with a custom parser, via `options.handler`. If the
    format isn't already supported, a custom parser can parse the file. This is
    useful for CSON, YAML, TOML, and nearly any other data format under the sun.
    This should future-proof this a little. (This includes XML, if you're
    willing to do the extra processing.)

  - Returning a no-op stream instead of undefined. This makes it a proper Gulp
    plugin, suitable for use in the middle of Gulp pipelines.
      - The previous behavior was somewhat surprising, since the package is called
        `gulp-env`. All it was was a standalone module, not even Gulp-friendly.
        Also, it didn't even have either of the `gulpplugin` or `gulpfriendly`
        keywords.

  - Some TypeScript definitions.

I also cleaned up a few existing examples in the README, but these are minor.

As for #5, here would be the proper solution:

```js
env({
  file: '.env',
  type: 'ini'
});
```

### CODE REVIEW

**Comment by russmatney** [comment]
Thanks for going ham on this! I'd merge your stuff and add you as a maintainer, or even encourage you to take it over yourself if you're willing. I no longer have write access to this repo, perhaps some of the nice moveliner devs will pick it up?

It all looks fantastic. I haven't pulled it but read through most, and if the tests pass, they pass.

I like the `env.set / env` alias. I'd struggled with the api to present, but hadn't gotten back to figuring it out. In truth, I don't use this anymore. Typically I only need to set one or two `process.env`s in the gulpfile, and the rest can be pulled into node via a config module, maybe something [like this](https://github.com/russmatney/configit). As a result, there are likely use-cases that I'm not aware of where expanding file-types will lower the overhead for people to start using this.

This was originally a tiny little module used to bring an old grunt tool over to a gulp flow we were trying out. It was also a demo shown at a meetup to bring the wall of intimidation down and encourage people to throw their own repos together. 

Biggest critique I'd have at this point is keeping that gigantic `node.d.ts` file behind version control for if/when it gets tweaked and needs updating. I'm also very partial to tiny modules when possible... but that's more a vanity concern than a practical one in this case.

**Comment by impinball** [comment]
That giant file is simply a dependency for gulp-env.d.ts. Sadly, TypeScript
doesn't have any sort of dependency management for definition files. And to
be honest, it rarely needs updated (I got it from DefinitelyTyped, and the
definition files for Node rarely get anything beyond bug fixes).

Although, if you could ping someone who has write access, that would be
awesome.

**Comment by impinball** [comment]
@RussMatney Ping...

**Comment by russmatney** [comment]
@impinball sorry for the delay here – I've reached out the old team, will get this resolved for you shortly.

Definitely recommending the merge, and also considering transferring the repo to you if you're interested in maintaining it – clearly it's not getting much attention over here.

It's no longer a part of my workflow at all – how are you using it these days? Curious what the use-case is.

**Comment by impinball** [comment]
@russmatney I'm not currently, but 1. there isn't really a viable alternative to `_.assign(process.env, vars)`, and 2. I know people want to use some of these features in the wild, since [I've already been contacted on Twitter by someone who thought this was already merged](https://twitter.com/SondreB/status/619439130389422080), complaining about broken .ini support that doesn't actually exist in the current npm package.

I would definitely integrate it after this merge, though. There's a few other nuts I'd love to crack, such as env push/pop, etc., so I can potentially use it like this in a very `gulp-filter`-like fashion:

```coffee
gulp.task 'build', ->
  gulp.src('dir')
    .pipe envs = env.set NODE_DEBUG: yes
    .pipe sourcemaps.init()
    .pipe coffee()
    .pipe inlineEnv() # another plugin on my bucket list
    .pipe uglify()
    .pipe sourcemaps.write('dist')
    .pipe gulp.dest('dest')
    .pipe envs.reset # cleanup environment variables
```

That would also make it invaluable with Babel and its `inlineEnvironmentVariables` option/associated plugin `babel-plugin-inline-vars`. I would use it daily after that.

I'm still definitely open for accepting ownership of it, though.

**Comment by impinball** [comment]
@russmatney Any news yet?

**Comment by impinball** [comment]
@crystalschang So I'm guessing the transfer isn't going to happen?

**Pull request merged**
